export const SET_APP_TITLE = 'SET_APP_TITLE'
export const SET_FAVORITES = 'SET_FAVORITES'

export const SET_FAVE = 'SET_FAVE'
export const SET_FAVE_RANK = 'SET_FAVE_RANK'
export const SET_FAVE_POSTER = 'SET_FAVE_POSTER'
export const SET_FAVE_TITLE = 'SET_FAVE_TITLE'
export const SET_FAVE_LINK = 'SET_FAVE_LINK'

export const APPEND_FAVE = 'APPEND_FAVE'
export const CLEAR_FAVE = 'CLEAR_FAVE'

export const SEARCH_TEXT = 'SEARCH_TEXT'
export const SEARCH_RESULTS = 'SEARCH_RESULTS'
export const CLEAR_SEARCHED_ALBUMS = 'CLEAR_SEARCHED_ALBUMS'

export const EDIT_RANK = 'EDIT_RANK'

export const DELETE_FAVE = 'DELETE_FAVE'

export const FAVORITES_SEARCH_RESULTS = 'FAVORITES_SEARCH_RESULTS'
